package git.chexson.chexsonsaeutils.crafting.directprocessing;

public enum MachineSupportReasonCode {
    NONE,
    NON_EXPLICIT_ADAPTER,
    MALFORMED_DATA,
    UNKNOWN_ENUM,
    REGISTRY_MISSING,
    PATTERN_DECODE_FAILED,
    SUBSTITUTION_INPUT,
    MULTIPLE_PATHS,
    MULTIPLE_PROVIDERS,
    MAPPING_MISSING,
    NAMING_CONVENTION_NEEDS_MAPPING,
    IDENTIFIED_RECIPE_TYPE_UNREADABLE,
    MAPPING_CONFLICT,
    DYNAMIC_RECIPE_SHAPE,
    RUNTIME_BUSY
}
